const Algae = require('../models/algae');

const algaeData = [
    {
        site_visit_date: '2021/06/24 17:08:00+00',
        location: 'Rodman Reservoir - Rodman Dam Road',
        county: 'Putman',
        algae_observed: 'no',
        comments: '',
        lat: 29.5210,
        lon: -81.1118,
        algae_type: 'Microcysts Aeruginosa',
        microcystin: 'pending',
        other_toxin: 'pending',
        pic_URL: '',
        toxin_present: 'pending',
    },
    {
        site_visit_date: '2021/06/24 17:08:00+00',
        location: 'C51 Canal- Military trail',
        county: 'Palm Beach',
        algae_observed: 'no',
        comments: '',
        lat: 26.6771,
        lon: -80.1118,
        algae_type: 'Mixed Algae',
        microcystin: 'No Dominant Species in Sample',
        other_toxin: 'No Dominant Species in Sample',
        pic_URL: '',
        toxin_present: 'pending',
    },
    {
        site_visit_date: '2021/06/23 17:08:00+00',
        location: 'Lake Sebring',
        county: 'Highlands',
        algae_observed: 'Yes',
        comments: 'blue; green; smells foul',
        lat: 27.5234,
        lon: -81.4786,
        algae_type: 'Mixed Algae',
        microcystin: 'No Dominant Species in Sample',
        other_toxin: 'Anatoxin-alpha: not detected',
        pic_URL: '',
        toxin_present: 'pending',
    },
    {
        site_visit_date: '2021/06/22 17:08:00+00',
        location: 'Tampa Bay - Piney 20',
        county: 'Hillsborough',
        algae_observed: 'no',
        comments: 'algae identified by FWRI',
        lat: 27.729,
        lon: -82.4987,
        algae_type: 'Mixed Algae',
        microcystin: 'No Dominant Species in Sample',
        other_toxin: 'No Dominant Species in Sample',
        pic_URL: '',
        toxin_present: 'no',
    },
    {
        site_visit_date: '2021/06/21 17:08:00+00',
        location: 'C43 canal S79 Upstrem',
        county: 'Lee',
        algae_observed: 'yes',
        comments: 'slight film on surface of water upstream',
        lat: 26.7228,
        lon: -81.6909,
        algae_type: 'Microcystis Aeruginosa',
        microcystin: '2.2 micrograms/l',
        other_toxin: 'anatoxin-alpha not detected; cylindrospermopsin detected',
        pic_URL: '',
        toxin_present: 'not detected',
    },
    {
        site_visit_date: '2021/06/17 17:08:00+00',
        location: 'Caloosahatchee River - S Olga dr',
        county: 'Lee',
        algae_observed: 'yes',
        comments: 'Slight film on the surface',
        lat: 26.7241,
        lon: -81.7125,
        algae_type: 'Dominant Microcystis Aeruginosa',
        microcystin: '0.82 micrograms/l',
        other_toxin: 'anatoxin-alpha not detected; cylindrospermopsin not detected',
        pic_URL: '',
        toxin_present: 'yes',
    },
    {
        site_visit_date: '2021/06/17 17:08:00+00',
        location: 'Caloosahatchee River - S Olga dr',
        county: 'Lee',
        algae_observed: 'yes',
        comments: 'Slight film on the surface',
        lat: 26.7241,
        lon: -81.7125,
        algae_type: 'Dominant Microcystis Aeruginosa',
        microcystin: '0.82 micrograms/l',
        other_toxin: 'anatoxin-alpha not detected; cylindrospermopsin not detected',
        pic_URL: '',
        toxin_present: 'yes',
    },
    {
        site_visit_date: '2021/06/17 17:08:00+00',
        location: 'Caloosahatchee River - Alva boat ramp',
        county: 'Lee',
        algae_observed: 'no',
        comments: '',
        lat: 26.71394,
        lon: -81.6061,
        algae_type: 'Dominant Microcystis Aeruginosa',
        microcystin: '0.87 micrograms/l',
        other_toxin: 'anatoxin-alpha not detected; cylindrospermopsin not detected',
        pic_URL: '',
        toxin_present: 'yes',
    },
    {
        site_visit_date: '2021/06/07 11:08:00+00',
        location: 'C43 canal - S79(upstream)',
        county: 'Lee',
        algae_observed: 'yes',
        comments: 'bright green particles visible in water column; ',
        lat: 26.7223,
        lon: -81.7498,
        algae_type: 'Dominant Microcystis Aeruginosa',
        microcystin: '0.64 micrograms/l',
        other_toxin: 'anatoxin-alpha not detected; cylindrospermopsin not detected',
        pic_URL: '',
        toxin_present: 'no',
    },
    {
        site_visit_date: '2021/06/03 11:08:00+00',
        location: 'Orange River - Manatee Park',
        county: 'Lee',
        algae_observed: 'yes',
        comments: 'small amounts of algae suspended in water column',
        lat: 26.6936,
        lon: -81.7776,
        algae_type: 'Dominant Cylindrospermopsin raciborskii',
        microcystin: '0.45 micrograms/l',
        other_toxin: 'anatoxin-alpha not detected; cylindrospermopsin not detected',
        pic_URL: '',
        toxin_present: 'no',
    },
    {
        site_visit_date: '2021/06/07 15:38:00+00',
        location: 'Caloosahatchee River - S Olga dr',
        county: 'Lee',
        algae_observed: 'yes',
        comments: 'algae suspended in water column',
        lat: 26.7241,
        lon: -81.7125,
        algae_type: 'Dominant Microcystis Aeruginosa',
        microcystin: '0.47 micrograms/l',
        other_toxin: 'anatoxin-alpha not detected; cylindrospermopsin not detected',
        pic_URL: '',
        toxin_present: 'no',
    },    
    {
        site_visit_date: '2021/06/07 14:45:00+00',
        location: 'Caloosahatchee River - Sebastian Ct Canal',
        county: 'Lee',
        algae_observed: 'yes',
        comments: 'algae suspended in water column',
        lat: 26.7129,
        lon: -81.6205,
        algae_type: 'Dominant Microcystis Aeruginosa',
        microcystin: '0.52 micrograms/l',
        other_toxin: 'anatoxin-alpha not detected; cylindrospermopsin not detected',
        pic_URL: '',
        toxin_present: 'no',
    },
    {
        site_visit_date: '2021/06/07 14:45:00+00',
        location: 'Caloosahatchee River - Davis Boat ramp',
        county: 'Lee',
        algae_observed: 'yes',
        comments: 'specks visible in water column/surface; slight acumulation on sea wall',
        lat: 26.7115,
        lon: -81.7533,
        algae_type: 'Dominant Microcystis Aeruginosa',
        microcystin: '0.52 micrograms/l',
        other_toxin: 'anatoxin-alpha not detected; cylindrospermopsin not detected',
        pic_URL: '',
        toxin_present: 'no',
    },
    {
        site_visit_date: '2021/06/01 13:55:00+00',
        location: 'Tampa Bay - Piney 20',
        county: 'Hillsborough',
        algae_observed: 'yes',
        comments: 'specks visible in water column/surface; slight acumulation on sea wall',
        lat: 27.729,
        lon: -82.4987,
        algae_type: 'Dominant Microcystis Aeruginosa',
        microcystin: '0.62 micrograms/l',
        other_toxin: 'anatoxin-alpha not detected; cylindrospermopsin not detected',
        pic_URL: '',
        toxin_present: 'no',
    },
    {
        site_visit_date: '2021/06/01 14:47:00+00',
        location: 'Tampa Bay - Piney 3',
        county: 'Hillsborough',
        algae_observed: 'no',
        comments: 'specks visible in water column/surface; slight acumulation on sea wall',
        lat: 27.6434,
        lon: -82.5639,
        algae_type: 'mixed algae',
        microcystin: '0.62 micrograms/l',
        other_toxin: 'no dominant species in sample',
        pic_URL: '',
        toxin_present: 'no',
    },
    
]

const seedAlgae = () => Algae.bulkCreate(algaeData, {individualHooks: true});

module.exports = seedAlgae;